# Website settings
title: "Me"
description: "Christian's personal website."
baseurl: "/"
url: "http://www.christian-vogel.me"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Christian'
  first_name: 'Christian'
  last_name: 'Vogel'
  email: 'me@christian-vogel.me'
  github: 'sichvoge'
  linkedin: 'vogelchristian'
  blog: 'https://medium.com/@ChristianVogel_'
  head_img: 'static/img/landing/Christian.jpg'
  desc: 'Product Manager @ CoreOS; ❤ Technology ❤ APIs ❤ Coding; Opinions == mine'

# Build settings
encoding: "utf-8"
